### ISSUE TITLE
Project Status?

### ISSUE THREAD

**Issue by proffalken** [gillg/OctoPrint-LDAP#27]
Hello!

I'm looking for a solution to manage user's in our Makerspace when it comes to accessing the 3D printer.

LDAP would be perfect, and so I'm wondering if this plugin is still maintained before I jump on it and start using it?

Thanks in advance!

**Comment by gillg** [comment]
Hello! I'm the creator of this plugin but I can't really say maintainer. I don't use octoprint since a long time that's the main reason why nothing move.
As you probably saw in some issues / pr, I try to let the community contribute if needed and I just keep an eye on the security aspect (to avoid this plug-in being a cryotominor ^^).

Any contribution is welcome, any bugfix too, until it's generic and donc break an existing usage.

So... The project is not dead but not super active neither.

**Comment by proffalken** [comment]
OK, thanks, I'll see if I need to make any changes!
