### ISSUE TITLE
Unable to make this work and/or see logfiles

### ISSUE THREAD

**Issue by giggls** [gillg/OctoPrint-LDAP#5]
Hello,

where is the errorlog of this module supposed to appear?

I'm trying to get this to work in an Active Directory environment with octopi.

While installing the plugin worked fine, logging in via ldap based accounts just looks like if your plugin functions are not even called. At least I can not see any output in octoprint.log and I can not log in using an ldap

**Comment by battis** [comment]
@giggls, I imagine this is a moot point now. And I'm about to post a version compatible with OctoPrint 1.4 in a few days. But, for posterity...

You need to set the logging level for OctoPrint to `DEBUG` and then look in the `logs/octoprint.log` file on your server, and you would see the errors being thrown. From experience, I would note that it's stupid hard to get good errors in the log, because subtle incorrectness in LDAP configuration results in opaque errors. [See my notes added to the README earlier this year.](https://github.com/gillg/OctoPrint-LDAP#search-base-gotcha)
